language: php

php:
  - 7.1
  - 7.2
  - 7.3
node_js:
  - 8
  - 9
  - 10

sudo: required

cache:
    directories:
        - $HOME/.composer/cache/files
# node_modules are not cached, because we don't shrinkwrap the deps.
#        - node_modules
env:
  matrix: SYMFONY_VERSION=4.2.*
  global:
    - SYMFONY_DEPRECATIONS_HELPER="/.*each.*/"
    - SYMFONY_PHPUNIT_DIR=.phpunit SYMFONY_PHPUNIT_REMOVE="symfony/yaml"
    - SYMFONY_PHPUNIT_VERSION=7
    - PHPUNIT_VERSION=7
    - TEST_INSTALLATION=false
    - LANG=php
    - NODE_RELEASE=6.x

matrix:
  include:
    - php: 7.2
      dist: trusty
      node_js: 8
      env: LANG=js
    - php: 7.2
      node_js: 9
      env: LANG=js
    - php: 7.2
      node_js: 10
      env: LANG=js
    - env: TARGET=lint
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_VERSION=3.4.* SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.2
      env: SYMFONY_VERSION=4.2
    - php: 7.3
      env: STABILITY="dev" SYMFONY_VERSION=4.3.*
  fast_finish: true
  allow_failures:
    - php: 7.3
      env: STABILITY="dev" SYMFONY_VERSION=4.3.*
    - env: TARGET=test_installation

before_install:
  - if [ "$LANG" = "js" ]; then npm run travis:install; fi
  - if [ "$LANG" = "php" ]; then phpenv config-rm xdebug.ini || true; fi
  - phpenv config-rm xdebug.ini || true
  - phpenv config-add travis.php.ini
  - php -ini | grep memory_limit
  - composer self-update
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; composer config prefer-stable true; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
 

install:
  - if [ -x .travis/install_${TARGET}.sh ]; then .travis/install_${TARGET}.sh; fi;

script:
  - if [ "$LANG" = "js" ]; then npm test; fi
  - if [ "$LANG" = "php" ]; then make $TARGET; fi
